// Cosmetics: slot/item definitions, head-anchor data, and equipped-state
// persistence. Extensible: hat / sunglasses / clothes / body slots, stack
// together. Adding a new item = adding an entry to COSMETIC_DEFS (plus its PNG).
//
// Everything here except createCosmetics().loadImages() is pure / storage-
// injected, so it runs under Node for tests.

import { EQUIPPED_COSMETICS_KEY } from '../config.js';

export const COSMETIC_SLOTS = ['hat', 'sunglasses', 'clothes', 'body']; // canonical slot list + menu tab order
export const COSMETIC_DRAW_ORDER = ['clothes', 'body', 'hat', 'sunglasses']; // back-to-front compositing order
export const COSMETIC_SLOT_LABELS = { hat: 'HAT', sunglasses: 'SUNGLASSES', clothes: 'SHOES', body: 'OUTFIT' }; // slot id stays 'clothes' for stored-state compatibility

export const COSMETIC_DEFS = {
  hat: [
    { id: 'wizard', name: 'Wizard Hat', image: 'png/hats/Purple Wizard Hat/pixel-art-purple-hat-free-png.png' },
    { id: 'tophat', name: 'Top Hat', image: 'png/hats/top-hat.png' },
    { id: 'cowboy', name: 'Cowboy Hat', image: 'png/hats/cowboy.png' },
    { id: 'crown', name: 'Crown', image: 'png/hats/crown.png' },
    { id: 'party', name: 'Party Hat', image: 'png/hats/party.png' },
    { id: 'beanie', name: 'Beanie', image: 'png/hats/beanie.png' },
  ],
  sunglasses: [
    { id: 'aviator', name: 'Aviators', image: 'png/sunglasses/aviator.png' },
    { id: 'pixel', name: 'Pixel Shades', image: 'png/sunglasses/pixel.png', offset: { scale: 0.27 } },
    { id: 'heart', name: 'Heart Glasses', image: 'png/sunglasses/heart.png', offset: { scale: 0.27 } },
    { id: 'visor', name: 'Sport Visor', image: 'png/sunglasses/visor.png', offset: { scale: 0.27 } },
    // The five below are generated by tools/gen-glasses.cjs.
    { id: 'star', name: 'Star Shades', image: 'png/sunglasses/star.png', offset: { scale: 0.46 } },
    { id: 'round', name: 'Reading Glasses', image: 'png/sunglasses/round.png', offset: { scale: 0.22 } },
    { id: '3d', name: '3D Glasses', image: 'png/sunglasses/3d.png', offset: { scale: 0.27 } },
    { id: 'shutter', name: 'Shutter Shades', image: 'png/sunglasses/shutter.png', offset: { scale: 0.27 } },
    { id: 'monocle', name: 'Monocle', image: 'png/sunglasses/monocle.png', offset: { scale: 0.30, dx: 36, dy: 55 } },
  ],
  // Shoes are per-frame overlays: full-size transparent PNGs generated from
  // the dog sprites with the paws recolored, one per animation frame (plus
  // the bite sheet). Drawn with the same geometry as the base frame, so they
  // track the feet exactly. `image` is only the menu tile icon.
  clothes: [
    { id: 'sneakers-red', name: 'Red Sneakers', image: 'png/clothes/sneakers-red/icon.png', frames: 'png/clothes/sneakers-red' },
    { id: 'sneakers-blue', name: 'Blue Sneakers', image: 'png/clothes/sneakers-blue/icon.png', frames: 'png/clothes/sneakers-blue' },
    { id: 'sneakers-green', name: 'Green Sneakers', image: 'png/clothes/sneakers-green/icon.png', frames: 'png/clothes/sneakers-green' },
    { id: 'sneakers-pink', name: 'Pink Sneakers', image: 'png/clothes/sneakers-pink/icon.png', frames: 'png/clothes/sneakers-pink' },
    { id: 'sneakers-gold', name: 'Gold Sneakers', image: 'png/clothes/sneakers-gold/icon.png', frames: 'png/clothes/sneakers-gold' },
    { id: 'sneakers-white', name: 'White Sneakers', image: 'png/clothes/sneakers-white/icon.png', frames: 'png/clothes/sneakers-white' },
  ],
  // Body outfits are per-frame overlays like the shoes (tutu generated by
  // tools/gen-tutu.cjs, the neck items by tools/gen-outfits.cjs), so they
  // track the torso/neck in every pose.
  body: [
    { id: 'tutu-pink', name: 'Pink Tutu', image: 'png/body/tutu-pink/icon.png', frames: 'png/body/tutu-pink' },
    { id: 'bandana-red', name: 'Red Bandana', image: 'png/body/bandana-red/icon.png', frames: 'png/body/bandana-red' },
    { id: 'cape-hero', name: 'Hero Cape', image: 'png/body/cape-hero/icon.png', frames: 'png/body/cape-hero' },
    { id: 'collar-green', name: 'Studded Collar', image: 'png/body/collar-green/icon.png', frames: 'png/body/collar-green' },
  ],
};

// Frame files for per-frame overlay items, matching loadDogSprites().
export const OVERLAY_FRAME_FILES = {
  run: ['dachshund_run_00.png', 'dachshund_run_01.png', 'dachshund_run_02.png'],
  jump: ['dachshund_jump_00.png', 'dachshund_jump_01.png', 'dachshund_jump_02.png'],
  doublejump: ['dachshund_flip_00.png', 'dachshund_flip_01.png', 'dachshund_flip_02.png'],
  slide: ['dachshund_pancake_00.png', 'dachshund_pancake_01.png', 'dachshund_pancake_02.png'],
};

// Where the dog's head is in each pose, in the same local 512x1024 sprite-pixel
// space as the base dachshund frames. Live-calibrated against the actual
// running game (screenshots + a static-render harness reproducing the exact
// drawCosmeticOverlay math), per pose and sub-frame.
export const HEAD_ANCHORS = {
  run:        [{ x: 340, y: 400, angle: -6 },  { x: 318, y: 402, angle: -3 },  { x: 303, y: 406, angle: -8 }],
  jump:       [{ x: 353, y: 330, angle: -15 }, { x: 343, y: 357, angle: -8 }, { x: 278, y: 387, angle: -3 }],
  doublejump: [{ x: 418, y: 482, angle: 20 },  { x: 313, y: 482, angle: -150 }], // index 2 reuses jump[2], see getHeadAnchor
  slide:      [{ x: 343, y: 462, angle: -4 },  { x: 318, y: 477, angle: -2 },  { x: 303, y: 482, angle: -4 }],
  bite:       [{ x: 338, y: 467, angle: -6 },  { x: 263, y: 367, angle: -25 }, { x: 343, y: 532, angle: -6 }],
};

// Per-slot fine-tune relative to the shared head anchor above (hat sits above
// the crown, sunglasses sit at eye level). Live-calibrated.
export const SLOT_ANCHOR_OFFSET = {
  hat:        { dx: 0,  dy: -38, angleOffset: 0, scale: 0.68 },
  sunglasses: { dx: 50, dy: 38,  angleOffset: 0, scale: 0.20 },
};

// Slot offset with any per-item `offset` fine-tune merged on top (an item's
// art may need a different scale or nudge than the slot default).
export function getItemAnchorOffset(slot, itemId) {
  const base = SLOT_ANCHOR_OFFSET[slot];
  const item = COSMETIC_DEFS[slot]?.find(i => i.id === itemId);
  return item?.offset ? { ...base, ...item.offset } : base;
}

// anim/frameIdx use the exact same values as getDogSpriteAnim()/dogSpriteFrame
// (or getDogJumpFrameIndex() for jump/doublejump) that drawDachshundSprite computes.
export function getHeadAnchor(anim, frameIdx) {
  if (anim === 'idle' || anim === 'dead') return HEAD_ANCHORS.run[0];
  if (anim === 'doublejump' && frameIdx === 2) return HEAD_ANCHORS.jump[2];
  const frames = HEAD_ANCHORS[anim];
  return frames[frameIdx % frames.length];
}

// Which overlay a per-frame item shows for a given base anim/frame; mirrors
// the base-sprite selection in drawDachshundSprite (idle/dead reuse run[0],
// doublejump frame 2 reuses jump[2], bite uses the sheet).
export function getOverlayFrame(entry, anim, frameIdx) {
  if (!entry || !entry.frames) return null;
  if (anim === 'bite') return null; // callers use entry.biteSheet + sheet drawing
  if (anim === 'idle' || anim === 'dead') return entry.frames.run[0];
  if (anim === 'doublejump' && frameIdx === 2) return entry.frames.jump[2];
  const frames = entry.frames[anim];
  return frames ? frames[frameIdx % frames.length] : null;
}

export function loadEquippedCosmetics(storage) {
  const fallback = { hat: null, sunglasses: null, clothes: null, body: null };
  try {
    const raw = storage.getItem(EQUIPPED_COSMETICS_KEY);
    if (!raw) return fallback;
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== 'object') return fallback;
    const result = { ...fallback };
    COSMETIC_SLOTS.forEach(slot => {
      if (typeof parsed[slot] === 'string') result[slot] = parsed[slot];
    });
    return result;
  } catch {
    return fallback;
  }
}

export function saveEquippedCosmetics(storage, state) {
  try {
    storage.setItem(EQUIPPED_COSMETICS_KEY, JSON.stringify(state));
  } catch (_) {}
}

// Runtime cosmetics service: equipped state + loaded overlay images.
export function createCosmetics(storage) {
  const imageById = { hat: {}, sunglasses: {}, clothes: {}, body: {} };
  const service = {
    equipped: loadEquippedCosmetics(storage),
    imageById,

    // Cosmetic overlay images. Anchor items (hats, sunglasses): one isolated
    // image, positioned at render time via HEAD_ANCHORS + SLOT_ANCHOR_OFFSET.
    // Per-frame items (item.frames set): a full-size overlay per dog frame
    // plus the bite sheet, drawn with the base sprite's geometry. Browser-only.
    loadImages() {
      COSMETIC_SLOTS.forEach(slot => {
        COSMETIC_DEFS[slot].forEach(item => {
          if (item.frames) {
            const load = file => {
              const img = new Image();
              img.src = `${item.frames}/${file}`;
              return img;
            };
            const frames = {};
            Object.entries(OVERLAY_FRAME_FILES).forEach(([anim, files]) => {
              frames[anim] = files.map(load);
            });
            imageById[slot][item.id] = { frames, biteSheet: load('bite_3_image_sequence.png') };
          } else {
            const img = new Image();
            img.src = item.image;
            imageById[slot][item.id] = img;
          }
        });
      });
    },

    select(slot, itemId) {
      service.equipped[slot] = itemId || null;
      saveEquippedCosmetics(storage, service.equipped);
    },

    // Debug 'H' key: toggle the default hat on/off.
    toggleDefaultHat() {
      const defaultHatId = COSMETIC_DEFS.hat[0]?.id ?? null;
      service.equipped.hat = service.equipped.hat ? null : defaultHatId;
      saveEquippedCosmetics(storage, service.equipped);
    },
  };
  return service;
}
